<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'routing.loader' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/Loader.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/FileLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/XmlFileLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/YamlFileLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/PhpFileLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/GlobFileLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/DirectoryLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/ObjectRouteLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/routing/Loader/DependencyInjection/ServiceRouterLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderResolverInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/LoaderResolver.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/Loader/DelegatingLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/FileLocatorInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/config/FileLocator.php';
require_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Config/FileLocator.php';

$a = ($this->privates['file_locator'] ?? $this->privates['file_locator'] = new \Symfony\Component\HttpKernel\Config\FileLocator(($this->services['kernel'] ?? $this->get('kernel')), ($this->targetDirs[3].'/src/Resources'), array(0 => ($this->targetDirs[3].'/src'))));

$b = new \Symfony\Component\Config\Loader\LoaderResolver();
$b->addLoader(new \Symfony\Component\Routing\Loader\XmlFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\YamlFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\PhpFileLoader($a));
$b->addLoader(new \Symfony\Component\Config\Loader\GlobFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\DirectoryLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\DependencyInjection\ServiceRouterLoader($this));

return $this->services['routing.loader'] = new \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader(($this->privates['controller_name_converter'] ?? $this->privates['controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser(($this->services['kernel'] ?? $this->get('kernel')))), $b);
