<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.finder' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParserInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/TemplateFilenameParser.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/CacheWarmer/TemplateFinderInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/CacheWarmer/TemplateFinder.php';

return $this->privates['templating.finder'] = new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplateFinder(($this->services['kernel'] ?? $this->get('kernel')), new \Symfony\Bundle\FrameworkBundle\Templating\TemplateFilenameParser(), ($this->targetDirs[3].'/src/Resources'));
