<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.name_parser' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParserInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParser.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/TemplateNameParser.php';

return $this->privates['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(($this->services['kernel'] ?? $this->get('kernel')));
