<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.slots' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/SlotsHelper.php';

return $this->privates['templating.helper.slots'] = new \Symfony\Component\Templating\Helper\SlotsHelper();
