<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerPo0JcxW\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerPo0JcxW/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerPo0JcxW\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPo0JcxW\srcDevDebugProjectContainer();
