<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\AdminBundle\Controller\LoginController' shared autowired service.

require_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/Controller.php';
require_once $this->targetDirs[3].'/src/AdminBundle/Controller/LoginController.php';

return $this->services['App\AdminBundle\Controller\LoginController'] = new \App\AdminBundle\Controller\LoginController();
