<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.engine.php' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ServiceLocator.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/GlobalVariables.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/EngineInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/PhpEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/EngineInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/PhpEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParserInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParser.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/TemplateNameParser.php';

$this->privates['templating.engine.php'] = $instance = new \Symfony\Bundle\FrameworkBundle\Templating\PhpEngine(($this->privates['templating.name_parser'] ?? $this->privates['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(($this->services['kernel'] ?? $this->get('kernel')))), new \Symfony\Component\DependencyInjection\ServiceLocator(array('templating.helper.actions' => function () {
    return ($this->privates['templating.helper.actions'] ?? $this->load(__DIR__.'/getTemplating_Helper_ActionsService.php'));
}, 'templating.helper.code' => function () {
    return ($this->privates['templating.helper.code'] ?? $this->load(__DIR__.'/getTemplating_Helper_CodeService.php'));
}, 'templating.helper.form' => function () {
    return ($this->privates['templating.helper.form'] ?? $this->load(__DIR__.'/getTemplating_Helper_FormService.php'));
}, 'templating.helper.request' => function () {
    return ($this->privates['templating.helper.request'] ?? $this->load(__DIR__.'/getTemplating_Helper_RequestService.php'));
}, 'templating.helper.router' => function () {
    return ($this->privates['templating.helper.router'] ?? $this->load(__DIR__.'/getTemplating_Helper_RouterService.php'));
}, 'templating.helper.session' => function () {
    return ($this->privates['templating.helper.session'] ?? $this->load(__DIR__.'/getTemplating_Helper_SessionService.php'));
}, 'templating.helper.slots' => function () {
    return ($this->privates['templating.helper.slots'] ?? $this->privates['templating.helper.slots'] = new \Symfony\Component\Templating\Helper\SlotsHelper());
}, 'templating.helper.stopwatch' => function () {
    return ($this->privates['templating.helper.stopwatch'] ?? $this->privates['templating.helper.stopwatch'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\StopwatchHelper(NULL));
})), ($this->services['templating.loader'] ?? $this->load(__DIR__.'/getTemplating_LoaderService.php')), new \Symfony\Bundle\FrameworkBundle\Templating\GlobalVariables($this));

$instance->setCharset('UTF-8');
$instance->setHelpers(array('slots' => 'templating.helper.slots', 'request' => 'templating.helper.request', 'session' => 'templating.helper.session', 'router' => 'templating.helper.router', 'actions' => 'templating.helper.actions', 'code' => 'templating.helper.code', 'form' => 'templating.helper.form', 'stopwatch' => 'templating.helper.stopwatch'));

return $instance;
