<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/EngineInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/StreamingEngineInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/twig-bridge/TwigEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/EngineInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/twig-bundle/TwigEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/DelegatingEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/DelegatingEngine.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParserInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/TemplateNameParser.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/TemplateNameParser.php';

$this->services['templating'] = $instance = new \Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine($this, array());

$instance->addEngine(new \Symfony\Bundle\TwigBundle\TwigEngine(($this->services['twig'] ?? $this->load(__DIR__.'/getTwigService.php')), ($this->privates['templating.name_parser'] ?? $this->privates['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(($this->services['kernel'] ?? $this->get('kernel')))), ($this->privates['templating.locator'] ?? $this->load(__DIR__.'/getTemplating_LocatorService.php'))));
$instance->addEngine(($this->privates['templating.engine.php'] ?? $this->load(__DIR__.'/getTemplating_Engine_PhpService.php')));

return $instance;
