<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.request' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/Helper/RequestHelper.php';

return $this->privates['templating.helper.request'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\RequestHelper(($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
