<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.actions' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/Helper/ActionsHelper.php';

return $this->privates['templating.helper.actions'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\ActionsHelper(($this->privates['fragment.handler'] ?? $this->load(__DIR__.'/getFragment_HandlerService.php')));
