<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/TemplateController.php';

return $this->services['Symfony\Bundle\FrameworkBundle\Controller\TemplateController'] = new \Symfony\Bundle\FrameworkBundle\Controller\TemplateController(($this->services['twig'] ?? $this->load(__DIR__.'/getTwigService.php')), ($this->services['templating'] ?? $this->load(__DIR__.'/getTemplatingService.php')));
