<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.helper.router' shared service.

require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/HelperInterface.php';
require_once $this->targetDirs[3].'/vendor/symfony/templating/Helper/Helper.php';
require_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/Helper/RouterHelper.php';

return $this->privates['templating.helper.router'] = new \Symfony\Bundle\FrameworkBundle\Templating\Helper\RouterHelper(($this->services['router'] ?? $this->getRouterService()));
